export {
  getCourse,
  updateCourse,
  createModule,
  renameModule,
  deleteModule,
  createLesson,
  updateLesson,
  deleteLesson,
  toggleLessonComplete,
  courseQueryKeys,
  useCourseQuery,
  useInvalidateCourse,
  useUpdateCourseMutation,
  useCreateModuleMutation,
  useRenameModuleMutation,
  useDeleteModuleMutation,
  useCreateLessonMutation,
  useUpdateLessonMutation,
  useDeleteLessonMutation,
  useToggleLessonCompleteMutation,
} from "./api";
export type { CourseView, CourseModule, Lesson, LessonInput } from "./api";
export {
  DEMO_VIDEO_URL,
  transformCourse,
  lessonFormSchema,
  LESSON_TITLE_MAX_LENGTH,
  MODULE_TITLE_MAX_LENGTH,
  type LessonFormData,
} from "./model";
